### ISSUE TITLE
Create Vagrant and VirtualBox provisioning repository and readme.md

### ISSUE THREAD

**Issue by ro31337** [devhq-io/hacktunnel#3]
As a developer I should be able to easily run HackTunnel/tests locally without dependencies/limitations on my own environment and without wasting time on installing required software.

Create public repository (hacktunnel-dev-box) with Vagrant provisioning scripts for Ubuntu Linux and with scripts for:
- Installing go language
- Installing redis
- Installing node.js
- Installing global node.js modules (if required)
- Installing phantomjs
- Installing other necessary software
- Cloning latest version
- Building latest version

After successful provisioning I should be able to see the message:

"Project was built and configured successfully, execute ./hacktunnel to start the server"

After installation I should be located at the directory with hacktunnel executable available.

**Comment by ultimatesolution** [comment]
Initial implementaiton of Vagrant devbox: https://github.com/ultimatesolution/vagrant-hacktunnel

**Comment by ultimatesolution** [comment]
PhantomJS should be installed manually
